{% set name = "pymongoarrow" %}
{% set version = "1.3.0" %}

# appease linter
{% if libarrow is undefined %}
{% set libarrow = "13" %}
{% endif %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymongoarrow/pymongoarrow-{{ version }}.tar.gz
  sha256: e409b7a2f388f6c3a8b82e164bcfa82d1a330ab0f891fa0945d1ba4c6f29f6f1

build:
  number: 1
  {% if libarrow.split(".")[0] | int < 13 %}
  # python 3.12 only supported for pyarrow >=13
  skip: true  # [py>=312]
  {% endif %}
  script:
    - set eux  # [unix]
    - export MONGO_NO_COPY_LIBARROW=1             # [unix]
    - export MONGO_LIBARROW_DIR="${PREFIX}/lib"   # [unix]
    - export MONGO_NO_COPY_LIBBSON=1              # [unix]
    - export LIBBSON_INSTALL_DIR="${PREFIX}"      # [unix]
    - export MONGO_CREATE_LIBARROW_SYMLINKS=""    # [unix]
    - export MONGO_ADD_GLIBCXX_OVERRIDE=""        # [unix]
    - set MONGO_NO_COPY_LIBARROW=1                # [win]
    - set "MONGO_LIBARROW_DIR=%LIBRARY_LIB%"      # [win]
    - set MONGO_NO_COPY_LIBBSON=1                 # [win]
    - set "LIBBSON_INSTALL_DIR=%LIBRARY_PREFIX%"  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - libarrow                               # [build_platform != target_platform]
    - pyarrow                                # [build_platform != target_platform]
    - libbson                                # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - pip
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

  host:
    - python
    - libarrow
    - {{ pin_compatible('pyarrow', max_pin='x') }}
    - cython >=0.29
    - libbson >=1,<2
    - pip
    - pkg-config
    - python

  run:
    - pymongo >=3.11,<5
    - {{ pin_compatible('pyarrow', max_pin='x') }}
    - python

test:
  source_files:
    - .
  files:
    - run_the_tests.sh
  requires:
    - pip
    - pandas
    - numpy
    - {{ pin_compatible('pyarrow', max_pin='x') }}
    - pytest
    # TODO: replace with mongodb install once https://github.com/conda-forge/mongodb-feedstock/pull/72 is resolved
    - icu
    - yaml-cpp
    - boost-cpp
    - curl

  commands:
    - bash run_the_tests.sh  # [osx]

about:
  home: https://pypi.org/project/pymongoarrow/
  summary: Tools for using NumPy, Pandas and PyArrow with MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - blink1073
    - ShaneHarvey
