{% set name = "pymongoarrow" %}
{% set version = "0.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pymongoarrow/pymongoarrow-{{ version }}.tar.gz
  sha256: 28d0d2b15a72b612c6533bed2a55d847b8b11500035f595ae7036f36d9f10c3c
  patches:
    - patches/0001-no-cxx-flags.patch

build:
  number: 2
  script:
    - set eux  # [unix]
    - export MONGO_NO_COPY_LIBARROW=1             # [unix]
    - export MONGO_LIBARROW_DIR="${PREFIX}/lib"   # [unix]
    - export MONGO_NO_COPY_LIBBSON=1              # [unix]
    - export LIBBSON_INSTALL_DIR="${PREFIX}"      # [unix]
    - export MONGO_CREATE_LIBARROW_SYMLINKS=""    # [unix]
    - set MONGO_NO_COPY_LIBARROW=1                # [win]
    - set "MONGO_LIBARROW_DIR=%LIBRARY_LIB%"      # [win]
    - set MONGO_NO_COPY_LIBBSON=1                 # [win]
    - set "LIBBSON_INSTALL_DIR=%LIBRARY_PREFIX%"  # [win]
    - {{ PYTHON }} -m pip install . --no-deps -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - arrow-cpp                              # [build_platform != target_platform]
    - pyarrow                                # [build_platform != target_platform]
    - libbson                                # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - setuptools >=47
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - arrow-cpp
    - cython >=0.29
    - libbson >=1,<2
    - pip
    - pyarrow >=7
    - pkg-config
    - python

  run:
    - pyarrow >=7
    - pymongo >=3.11,<5
    - arrow-cpp
    - python

test:
  source_files:
    - .
  files:
    - run_the_tests.sh
  requires:
    - pip
    - pandas
    - numpy
    - pyarrow
    - mongodb     # [not win]
  commands:
    - bash run_the_tests.sh  # [unix and not (ppc64le or python_impl=='pypy')]

about:
  home: https://pypi.org/project/pymongoarrow/
  summary: Tools for using NumPy, Pandas and PyArrow with MongoDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - blink1073
    - ShaneHarvey
